/** Stable API error codes returned as `{ error: { code } }`. */
export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_REFRESH: "INVALID_REFRESH",
  SESSION_STALE: "SESSION_STALE",
  NO_PASSWORD: "NO_PASSWORD",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  RATE_LIMITED: "RATE_LIMITED",

  // Access
  FORBIDDEN: "FORBIDDEN",
  ORG_REQUIRED: "ORG_REQUIRED",
  ORG_LIMIT: "ORG_LIMIT",
  SHOP_SECTOR_REQUIRED: "SHOP_SECTOR_REQUIRED",
  INVALID_BRANCH: "INVALID_BRANCH",
  ORG_WRONG_VERTICAL: "ORG_WRONG_VERTICAL",
  MODULE_PLAN_LOCKED: "MODULE_PLAN_LOCKED",
  ORG_SETUP_INCOMPLETE: "ORG_SETUP_INCOMPLETE",

  // Generic
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN: "UNKNOWN",
  BUSINESS_RULE: "BUSINESS_RULE",

  // Billing & cloud
  PLAN_UPGRADE_REQUIRED: "PLAN_UPGRADE_REQUIRED",
  CLOUD_DISABLED: "CLOUD_DISABLED",
  SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",
  ALREADY_CANCELLED: "ALREADY_CANCELLED",
  CONFIRM_MISMATCH: "CONFIRM_MISMATCH",

  // Desktop
  NO_DATA: "NO_DATA",
  INVALID_PAIRING: "INVALID_PAIRING",
  PAIRING_EXPIRED: "PAIRING_EXPIRED",

  // Files
  NO_FILE: "NO_FILE",
  INVALID_FILE: "INVALID_FILE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",

  // Domain-specific
  DUPLICATE_EXPENSE: "DUPLICATE_EXPENSE",
  UNKNOWN_KIND: "UNKNOWN_KIND",

  // Internal / infra (rarely shown)
  CORS_FORBIDDEN: "CORS_FORBIDDEN",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
